# Generated by Django 6.0.5 on 2026-05-08 15:54

import apps.surgery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryPackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('info_pending', 'Info Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='info_pending', max_length=20)),
                ('tentative_date', models.DateField()),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hospitals.surgerypackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bookings', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='coupons/qr/')),
                ('voucher_pdf', models.FileField(blank=True, null=True, upload_to='coupons/pdf/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='surgery.surgerypackagebooking')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_country', models.CharField(max_length=80)),
                ('passport_expiry', models.DateField()),
                ('visa_required', models.BooleanField(default=False)),
                ('visa_status', models.CharField(choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('granted', 'Granted'), ('not_required', 'Not Required')], default='not_required', max_length=15)),
                ('current_occupation', models.CharField(max_length=150)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('annual_income_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('companion_count', models.PositiveSmallIntegerField(default=0)),
                ('companion_details', models.TextField(blank=True)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info', to='surgery.surgerypackagebooking')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('govt_id', 'Government ID'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to=apps.surgery.models._travel_doc_path)),
                ('doc_number', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='surgery.surgerypackagebooking')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
