# Generated by Django 6.0.5 on 2026-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0002_surgeryrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryrecommendation',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryrecommendation',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_admin', max_length=20),
        ),
    ]
