# Generated by Django 6.0.5 on 2026-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0004_recommendationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationmessage',
            name='read_by_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendationmessage',
            name='thread_type',
            field=models.CharField(choices=[('doctor', 'Doctor Thread'), ('patient', 'Patient Thread')], db_index=True, default='doctor', help_text='Which conversation this message belongs to (admin↔doctor or admin↔patient).', max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendationmessage',
            name='sender_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
    ]
