# Generated by Django 6.0.5 on 2026-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
