# Generated by Django 6.0.5 on 2026-05-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('recurring_weekly', 'Recurring Weekly'), ('specific_date', 'Specific Date')], max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctors.doctorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='doctors_doc_doctor__9bf760_idx'), models.Index(fields=['doctor', 'specific_date', 'is_active'], name='doctors_doc_doctor__1f3882_idx')],
            },
        ),
    ]
