# Generated by Django 6.0.5 on 2026-05-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitals/')),
                ('accreditations', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('is_partner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('surgery_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_duration_days', models.PositiveSmallIntegerField()),
                ('hospital_stay_days', models.PositiveSmallIntegerField()),
                ('recovery_stay_days', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes_flight', models.BooleanField(default=False)),
                ('flight_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business')], default='economy', max_length=10)),
                ('includes_visa_assistance', models.BooleanField(default=False)),
                ('includes_accommodation', models.BooleanField(default=False)),
                ('accommodation_type', models.CharField(choices=[('hotel_3star', '3-Star Hotel'), ('hotel_4star', '4-Star Hotel'), ('serviced_apt', 'Serviced Apartment')], default='hotel_3star', max_length=15)),
                ('includes_transport', models.BooleanField(default=False)),
                ('includes_meals', models.BooleanField(default=False)),
                ('inclusions_text', models.TextField(blank=True, help_text='One item per line')),
                ('exclusions_text', models.TextField(blank=True, help_text='One item per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['price_usd'],
            },
        ),
    ]
